<a href="https://colab.research.google.com/github/aditigupta217/Machine_Learning_/blob/main/day9.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#Encoding Categorical data , ordinal encoding --> transfer to numerical data ( only categorical data -> ordinal data (A>B>C))

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
df = pd.read_csv("customer.csv")

In [4]:
df.head()

   age  gender   review education purchased
0   30  Female  Average    School        No
1   68  Female     Poor        UG        No
2   70  Female     Good        PG        No
3   72  Female     Good        PG        No
4   16  Female  Average        UG        No

In [5]:
df = df.iloc[:,2:]

In [6]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(df.iloc[:,0:2], df.iloc[:,-1] ,test_size=0.2)

In [7]:
X_train

     review education
45     Poor        PG
31     Poor    School
28     Poor    School
22     Poor        PG
30  Average        UG
23     Good    School
4   Average        UG
29  Average        UG
42     Good        PG
2      Good        PG
12     Poor    School
5   Average    School
19     Poor        PG
41     Good        PG
44  Average        UG
10     Good        UG
16     Poor        UG
9      Good        UG
35     Poor    School
8   Average        UG
0   Average    School
3      Good        PG
7      Poor    School
39     Poor        PG
18     Good    School
6      Good    School
14     Poor        PG
37  Average        PG
1      Poor        UG
40     Good    School
11     Good        UG
46     Poor        PG
38     Good    School
26     Poor        PG
13  Average    School
27     Poor        PG
24  Average        PG
33     Good        PG
49     Good        UG
21  Average        PG

In [8]:
from sklearn.preprocessing import OrdinalEncoder

In [9]:
oe = OrdinalEncoder(categories=[['Poor','Average','Good'],['School','UG','PG']])

In [10]:
oe.fit(X_train)

OrdinalEncoder(categories=[['Poor', 'Average', 'Good'], ['School', 'UG', 'PG']])

In [11]:
X_train = oe.transform(X_train)
X_test = oe.transform(X_test)

In [12]:
X_train

array([[0., 2.],
       [0., 0.],
       [0., 0.],
       [0., 2.],
       [1., 1.],
       [2., 0.],
       [1., 1.],
       [1., 1.],
       [2., 2.],
       [2., 2.],
       [0., 0.],
       [1., 0.],
       [0., 2.],
       [2., 2.],
       [1., 1.],
       [2., 1.],
       [0., 1.],
       [2., 1.],
       [0., 0.],
       [1., 1.],
       [1., 0.],
       [2., 2.],
       [0., 0.],
       [0., 2.],
       [2., 0.],
       [2., 0.],
       [0., 2.],
       [1., 2.],
       [0., 1.],
       [2., 0.],
       [2., 1.],
       [0., 2.],
       [2., 0.],
       [0., 2.],
       [1., 0.],
       [0., 2.],
       [1., 2.],
       [2., 2.],
       [2., 1.],
       [1., 2.]])

In [ ]:
# one hot encoding ( categorical -- nominal )

In [13]:
df = pd.read_csv('cars.csv')

In [14]:
df.head()

     brand  km_driven    fuel         owner  selling_price
0   Maruti     145500  Diesel   First Owner         450000
1    Skoda     120000  Diesel  Second Owner         370000
2    Honda     140000  Petrol   Third Owner         158000
3  Hyundai     127000  Diesel   First Owner         225000
4   Maruti     120000  Petrol   First Owner         130000

In [ ]:
df['brand'].value_counts()

brand
Maruti           2448
Hyundai          1415
Mahindra          772
Tata              734
Toyota            488
Honda             467
Ford              397
Chevrolet         230
Renault           228
Volkswagen        186
BMW               120
Skoda             105
Nissan             81
Jaguar             71
Volvo              67
Datsun             65
Mercedes-Benz      54
Fiat               47
Audi               40
Lexus              34
Jeep               31
Mitsubishi         14
Land                6
Force               6
Isuzu               5
Ambassador          4
Kia                 4
MG                  3
Daewoo              3
Ashok               1
Opel                1
Peugeot             1
Name: count, dtype: int64

In [15]:
df['fuel'].value_counts()

fuel
Diesel    4402
Petrol    3631
CNG         57
LPG         38
Name: count, dtype: int64

In [16]:
df['owner'].value_counts()

owner
First Owner             5289
Second Owner            2105
Third Owner              555
Fourth & Above Owner     174
Test Drive Car             5
Name: count, dtype: int64

In [17]:
# using pandas one hot encoding
pd.get_dummies(df, columns=['fuel','owner'])

,brand,km_driven,selling_price,fuel_CNG,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_First Owner,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,Maruti,145500,450000,False,True,False,False,True,False,False,False,False
1,Skoda,120000,370000,False,True,False,False,False,False,True,False,False
2,Honda,140000,158000,False,False,False,True,False,False,False,False,True
3,Hyundai,127000,225000,False,True,False,False,True,False,False,False,False
4,Maruti,120000,130000,False,False,False,True,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai,110000,320000,False,False,False,True,True,False,False,False,False
8124,Hyundai,119000,135000,False,True,False,False,False,True,False,False,False
8125,Maruti,120000,382000,False,True,False,False,True,False,False,False,False
8126,Tata,25000,290000,False,True,False,False,True,False,False,False,False
8127,Tata,25000,290000,False,True,False,False,True,False,False,False,False

In [20]:
# k-1 onehot encoding
pd.get_dummies(df, columns=['fuel','owner'], drop_first=True)

,brand,km_driven,selling_price,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,Maruti,145500,450000,True,False,False,False,False,False,False
1,Skoda,120000,370000,True,False,False,False,True,False,False
2,Honda,140000,158000,False,False,True,False,False,False,True
3,Hyundai,127000,225000,True,False,False,False,False,False,False
4,Maruti,120000,130000,False,False,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai,110000,320000,False,False,True,False,False,False,False
8124,Hyundai,119000,135000,True,False,False,True,False,False,False
8125,Maruti,120000,382000,True,False,False,False,False,False,False
8126,Tata,25000,290000,True,False,False,False,False,False,False
8127,Tata,25000,290000,True,False,False,False,False,False,False

In [18]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(df.iloc[:,0:4], df.iloc[:,-1] ,test_size=0.2)

In [19]:
X_train

              brand  km_driven    fuel         owner
5407           Ford      40000  Diesel   First Owner
7680         Maruti     120000  Diesel   Third Owner
4345          Honda      28000  Petrol   First Owner
6690          Lexus      20000  Petrol   First Owner
8091           Fiat      40000  Petrol  Second Owner
...             ...        ...     ...           ...
1128        Hyundai      56290  Diesel   First Owner
1268        Renault      65000  Diesel   First Owner
4801           Tata      60000  Diesel  Second Owner
6155         Maruti     100000  Petrol   Third Owner
141   Mercedes-Benz      35000  Diesel   First Owner

[6502 rows x 4 columns]

In [21]:
# from sklearn lib - onehot encoding
from sklearn.preprocessing import OneHotEncoder

In [22]:
ohe = OneHotEncoder()

In [23]:
X_train_new = ohe.fit_transform(X_train[['fuel','owner']]).toarray()

In [24]:
X_test_new = ohe.transform(X_train[['fuel','owner']]).toarray()

In [25]:
X_test_new

array([[0., 1., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 1., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 1., 0., ..., 0., 0., 0.]])

In [26]:
np.hstack((X_train[['brand', 'km_driven']].values,X_train_new)).shape

(6502, 11)

In [27]:
# for brand
count = df['brand'].value_counts()

In [28]:
df['brand'].nunique()
threshold = 100

In [29]:
repl = count[count <= threshold].index

In [30]:
pd.get_dummies(df['brand']. replace(repl, 'uncommon' ))

,BMW,Chevrolet,Ford,Honda,Hyundai,Mahindra,Maruti,Renault,Skoda,Tata,Toyota,Volkswagen,uncommon
0,False,False,False,False,False,False,True,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,True,False,False,False,False
2,False,False,False,True,False,False,False,False,False,False,False,False,False
3,False,False,False,False,True,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,True,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
8123,False,False,False,False,True,False,False,False,False,False,False,False,False
8124,False,False,False,False,True,False,False,False,False,False,False,False,False
8125,False,False,False,False,False,False,True,False,False,False,False,False,False
8126,False,False,False,False,False,False,False,False,False,True,False,False,False
8127,False,False,False,False,False,False,False,False,False,True,False,False,False